package table

type contracted struct {
	roman1     string
	roman2     string
	contracted string
}

var contractedList = []contracted{
	{ roman1: "bi", roman2: "xya", contracted: "bya" },
	{ roman1: "bi", roman2: "xyo", contracted: "byo" },
	{ roman1: "bi", roman2: "xyu", contracted: "byu" },
	{ roman1: "chi", roman2: "xya", contracted: "cha" },
	{ roman1: "chi", roman2: "xyo", contracted: "cho" },
	{ roman1: "chi", roman2: "xyu", contracted: "chu" },
	{ roman1: "gi", roman2: "xya", contracted: "gya" },
	{ roman1: "gi", roman2: "xyo", contracted: "gyo" },
	{ roman1: "gi", roman2: "xyu", contracted: "gyu" },
	{ roman1: "hi", roman2: "xya", contracted: "hya" },
	{ roman1: "hi", roman2: "xyo", contracted: "hyo" },
	{ roman1: "hi", roman2: "xyu", contracted: "hyu" },
	{ roman1: "ji", roman2: "xya", contracted: "ja" },
	{ roman1: "ji", roman2: "xyo", contracted: "jo" },
	{ roman1: "ji", roman2: "xyu", contracted: "ju" },
	{ roman1: "ki", roman2: "xya", contracted: "kya" },
	{ roman1: "ki", roman2: "xyo", contracted: "kyo" },
	{ roman1: "ki", roman2: "xyu", contracted: "kyu" },
	{ roman1: "mi", roman2: "xya", contracted: "mya" },
	{ roman1: "mi", roman2: "xyo", contracted: "myo" },
	{ roman1: "mi", roman2: "xyu", contracted: "myu" },
	{ roman1: "ni", roman2: "xya", contracted: "nya" },
	{ roman1: "ni", roman2: "xyo", contracted: "nyo" },
	{ roman1: "ni", roman2: "xyu", contracted: "nyu" },
	{ roman1: "pi", roman2: "xya", contracted: "pya" },
	{ roman1: "pi", roman2: "xyo", contracted: "pyo" },
	{ roman1: "pi", roman2: "xyu", contracted: "pyu" },
	{ roman1: "ri", roman2: "xya", contracted: "rya" },
	{ roman1: "ri", roman2: "xyo", contracted: "ryo" },
	{ roman1: "ri", roman2: "xyu", contracted: "ryu" },
	{ roman1: "shi", roman2: "xya", contracted: "sha" },
	{ roman1: "shi", roman2: "xyo", contracted: "sho" },
	{ roman1: "shi", roman2: "xyu", contracted: "shu" },
	}

var mapCharacters = map[string]string{
	"ア": "a",
	"イ": "i",
	"ウ": "u",
	"エ": "e",
	"オ": "o",
	"カ": "ka",
	"キ": "ki",
	"ク": "ku",
	"ケ": "ke",
	"コ": "ko",
	"サ": "sa",
	"シ": "shi",
	"ス": "su",
	"セ": "se",
	"ソ": "so",
	"タ": "ta",
	"チ": "chi",
	"ツ": "tsu",
	"テ": "te",
	"ト": "to",
	"ナ": "na",
	"ニ": "ni",
	"ヌ": "nu",
	"ネ": "ne",
	"ノ": "no",
	"ハ": "ha",
	"ヒ": "hi",
	"フ": "fu",
	"ヘ": "he",
	"ホ": "ho",
	"マ": "ma",
	"ミ": "mi",
	"ム": "mu",
	"メ": "me",
	"モ": "mo",
	"ヤ": "ya",
	"ユ": "yu",
	"ヨ": "yo",
	"ラ": "ra",
	"リ": "ri",
	"ル": "ru",
	"レ": "re",
	"ロ": "ro",
	"ワ": "wa",
	"ヰ": "i",
	"ヱ": "e",
	"ヲ": "o",
	"ガ": "ga",
	"ギ": "gi",
	"グ": "gu",
	"ゲ": "ge",
	"ゴ": "go",
	"ザ": "za",
	"ジ": "ji",
	"ズ": "zu",
	"ゼ": "ze",
	"ゾ": "zo",
	"ダ": "da",
	"ヂ": "ji",
	"ヅ": "zu",
	"デ": "de",
	"ド": "do",
	"バ": "ba",
	"ビ": "bi",
	"ブ": "bu",
	"ベ": "be",
	"ボ": "bo",
	"パ": "pa",
	"ピ": "pi",
	"プ": "pu",
	"ペ": "pe",
	"ポ": "po",
	"ァ": "a",
	"ィ": "i",
	"ゥ": "u",
	"ェ": "e",
	"ォ": "o",
	"ヵ": "ka",
	"ヶ": "ke",
	"ッ": "xtsu",
	"ャ": "xya",
	"ュ": "xyu",
	"ョ": "xyo",
	"ヮ": "wa",
	"ン": "n",
	"ヴ": "bu",
	"ー": "",
	}

/* Copyright 2021 Spiegel
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * 	http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
