package table

type contracted struct {
	roman1     string
	roman2     string
	contracted string
}

var contractedList = []contracted{
	{ roman1: "bi", roman2: "xya", contracted: "bya" },
	{ roman1: "bi", roman2: "xyo", contracted: "byo" },
	{ roman1: "bi", roman2: "xyu", contracted: "byu" },
	{ roman1: "chi", roman2: "xya", contracted: "cha" },
	{ roman1: "chi", roman2: "xyo", contracted: "cho" },
	{ roman1: "chi", roman2: "xyu", contracted: "chu" },
	{ roman1: "gi", roman2: "xya", contracted: "gya" },
	{ roman1: "gi", roman2: "xyo", contracted: "gyo" },
	{ roman1: "gi", roman2: "xyu", contracted: "gyu" },
	{ roman1: "hi", roman2: "xya", contracted: "hya" },
	{ roman1: "hi", roman2: "xyo", contracted: "hyo" },
	{ roman1: "hi", roman2: "xyu", contracted: "hyu" },
	{ roman1: "ji", roman2: "xya", contracted: "ja" },
	{ roman1: "ji", roman2: "xyo", contracted: "jo" },
	{ roman1: "ji", roman2: "xyu", contracted: "ju" },
	{ roman1: "ki", roman2: "xya", contracted: "kya" },
	{ roman1: "ki", roman2: "xyo", contracted: "kyo" },
	{ roman1: "ki", roman2: "xyu", contracted: "kyu" },
	{ roman1: "mi", roman2: "xya", contracted: "mya" },
	{ roman1: "mi", roman2: "xyo", contracted: "myo" },
	{ roman1: "mi", roman2: "xyu", contracted: "myu" },
	{ roman1: "ni", roman2: "xya", contracted: "nya" },
	{ roman1: "ni", roman2: "xyo", contracted: "nyo" },
	{ roman1: "ni", roman2: "xyu", contracted: "nyu" },
	{ roman1: "pi", roman2: "xya", contracted: "pya" },
	{ roman1: "pi", roman2: "xyo", contracted: "pyo" },
	{ roman1: "pi", roman2: "xyu", contracted: "pyu" },
	{ roman1: "ri", roman2: "xya", contracted: "rya" },
	{ roman1: "ri", roman2: "xyo", contracted: "ryo" },
	{ roman1: "ri", roman2: "xyu", contracted: "ryu" },
	{ roman1: "shi", roman2: "xya", contracted: "sha" },
	{ roman1: "shi", roman2: "xyo", contracted: "sho" },
	{ roman1: "shi", roman2: "xyu", contracted: "shu" },
	}

var mapCharacters = map[string]string{
	"あ": "a",
	"い": "i",
	"う": "u",
	"え": "e",
	"お": "o",
	"か": "ka",
	"き": "ki",
	"く": "ku",
	"け": "ke",
	"こ": "ko",
	"さ": "sa",
	"し": "shi",
	"す": "su",
	"せ": "se",
	"そ": "so",
	"た": "ta",
	"ち": "chi",
	"つ": "tsu",
	"て": "te",
	"と": "to",
	"な": "na",
	"に": "ni",
	"ぬ": "nu",
	"ね": "ne",
	"の": "no",
	"は": "ha",
	"ひ": "hi",
	"ふ": "fu",
	"へ": "he",
	"ほ": "ho",
	"ま": "ma",
	"み": "mi",
	"む": "mu",
	"め": "me",
	"も": "mo",
	"や": "ya",
	"ゆ": "yu",
	"よ": "yo",
	"ら": "ra",
	"り": "ri",
	"る": "ru",
	"れ": "re",
	"ろ": "ro",
	"わ": "wa",
	"ゐ": "i",
	"ゑ": "e",
	"を": "o",
	"が": "ga",
	"ぎ": "gi",
	"ぐ": "gu",
	"げ": "ge",
	"ご": "go",
	"ざ": "za",
	"じ": "ji",
	"ず": "zu",
	"ぜ": "ze",
	"ぞ": "zo",
	"だ": "da",
	"ぢ": "ji",
	"づ": "zu",
	"で": "de",
	"ど": "do",
	"ば": "ba",
	"び": "bi",
	"ぶ": "bu",
	"べ": "be",
	"ぼ": "bo",
	"ぱ": "pa",
	"ぴ": "pi",
	"ぷ": "pu",
	"ぺ": "pe",
	"ぽ": "po",
	"ぁ": "a",
	"ぃ": "i",
	"ぅ": "u",
	"ぇ": "e",
	"ぉ": "o",
	"ゕ": "ka",
	"ゖ": "ke",
	"っ": "xtsu",
	"ゃ": "xya",
	"ゅ": "xyu",
	"ょ": "xyo",
	"ゎ": "wa",
	"ん": "n",
	"ゔ": "bu",
	"ー": "",
	}

/* Copyright 2021 Spiegel
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * 	http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
